language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_tensorflow_embedding"
policies:
  - name: "EmbeddingPolicy"
    epochs: 50
    attn_shift_range: 3
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer
  - name: MemoizationPolicy
    max_history: 6
  - name: FormPolicy
