
language: en
pipeline: supervised_embeddings

policies:
  - name: "EmbeddingPolicy"
    epochs: 50
    attn_shift_range: 3
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer
  - name: MemoizationPolicy
    max_history: 6
  - name: FormPolicy
